"""empty message

Revision ID: 269ca2591256
Revises: a3de93d89c9a
Create Date: 2024-12-04 11:10:24.439076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269ca2591256'
down_revision = 'a3de93d89c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('api_key', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'api_key')
    # ### end Alembic commands ###
