"""empty message

Revision ID: 8822b27fecd6
Revises: 14b057de5335
Create Date: 2024-07-15 15:49:01.564813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8822b27fecd6'
down_revision = '14b057de5335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
