"""empty message

Revision ID: adb7005508cd
Revises: 3ee178e3c8f7
Create Date: 2024-06-26 11:23:58.010752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb7005508cd'
down_revision = '3ee178e3c8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curso', sa.Column('formacao_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'curso', 'formacao', ['formacao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'curso', type_='foreignkey')
    op.drop_column('curso', 'formacao_id')
    # ### end Alembic commands ###
